---
abstract: 'We are Polish CPAN authors'
author:
  - 'Przemyslaw Wesolek <jest@go.art.pl>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Polish
requires:
  Acme::CPANAuthors: 0
  Acme::CPANAuthors::Register: 0
resources:
  bugtracker: https://github.com/jest/perl.mod.Acme-CPANAuthors-Polish/issues
  repository: git://github.com/jest/perl.mod.Acme-CPANAuthors-Polish.git
version: 0.03
